apiVersion: v1
kind: Pod
metadata:
  name: postgresdb-pod
  labels:
    app: postgresdb
    tier: back-end
spec:
  containers:
  - name: postgres-db
    image: postgres
    ports:
        - containerPort: 5432
    env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"