apiVersion: apps/v1
kind: Deployment
metadata:
    name: redisapp-deployment
    labels:
        name: redisapp-deploy
        app: redisapp
spec:
    replicas: 1
    selector:
        matchLabels:
          name: redis-pod
          app: redisapp
    template:
      metadata:
        name: redis-pod
        labels:
          name: redis-pod
          app: redisapp
      spec:
        containers:
        - name: redis
          image: redis
          ports:
              - containerPort: 6379