apiVersion: v1
kind: Pod
metadata:
  name: votingapp-pod
  labels:
    app: votingapp
    tier: front-end
spec:
  containers:
  - name: voting-app
    image: kodekloud/examplevotingapp_vote:v1
    ports:
        - containerPort: 80