apiVersion: apps/v1
kind: Deployment
metadata:
    name: votingapp-deployment
    labels:
        name: votingapp-deploy
        app: votingapp
spec:
    replicas: 1
    selector:
        matchLabels:
               app: votingapp
               tier: front-end 
    template:
        metadata:
          name: votingapp-pod
          labels:
              app: votingapp
              tier: front-end
        spec:
          containers:
          - name: voting-app
            image: kodekloud/examplevotingapp_vote:v1
            ports:
              - containerPort: 80