apiVersion: v1
kind: Service
metadata:
    name: voting-service
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30004
    selector:
     app: votingapp
     tier: front-end